// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/4/12 15:00:55
const configMerger = require("C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/plugins/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/composables/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/utils/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/新建文件夹/official-nuxt/app.config.{js,ts,mjs}"] } }));

module.exports = config
